
services:
  backend:
    build: "java/simple-api-student"
    networks:
      - my-network
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_URL=${DB_URL}
      - DB_USR=${DB_USR}
      - DB_PWD=${DB_PWD}

  database:
    build: "database"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USR}
      - POSTGRES_PASSWORD=${DB_PWD}

  httpd:
    build: "httpd"
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

  frontend:
    build: "../tp-3/devops-front"
    ports:
      - "3000:80"  # Change ce port si nécessaire
    networks:
      - my-network
    depends_on:
      - backend



networks:
  my-network:

volumes:
  postgres-data:
