---
- name: Déployer le conteneur Frontend
  docker_container:
    name: frontend
    image: mathieuc71/frontend-cpe:latest # Remplace par l'image correcte si besoin
    pull: yes
    networks:
      - name: proxy-network
    restart_policy: always
    state: started
