name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Test Backend"]
    branches:
      - main
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get current version
        id: version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | awk -F. -v OFS=. '{$NF++; print}')" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/java/simple-api-student
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-cpe:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-cpe:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/database-cpe:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/database-cpe:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/httpd
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/httpd-cpe:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/httpd-cpe:latest
          push: true
