name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Test Backend"]
    branches:
      - main
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write  # 🔥 Autorise le push dans le rep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Get current version from pom.xml
        id: version
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" tp-1/java/simple-api-student/pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ env.VERSION }}
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update pom.xml with new version
        run: |
          sed -i "s|<version>${{ env.VERSION }}</version>|<version>${{ env.NEW_VERSION }}</version>|g" tp-1/java/simple-api-student/pom.xml

      - name: Commit and push new version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tp-1/java/simple-api-student/pom.xml
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push origin main --tags

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/java/simple-api-student
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-cpe:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-cpe:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/database-cpe:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/database-cpe:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: tp-1/httpd
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/httpd-cpe:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/httpd-cpe:latest
          push: true

      - name: Build and push front image
        uses: docker/build-push-action@v3
        with:
          context: tp-3/devops-front
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-cpe:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-cpe:latest
          push: true

#      - name: Deploy to Production
#        uses: appleboy/ansible-playbook-action@v1.4.2
#        with:
#          playbook: deploy.yml
#          inventory: inventory
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          remote_user: admin
#          host: ${{ secrets.HOST_CPE }}
#
#      - name: Run Ansible Playbook
#        env:
#          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
#          ANSIBLE_HOST_KEY_CHECKING: False
#        run: |
#          ansible-playbook -i inventory/hosts.ini playbooks/deploy_web_server.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}

      - name: Deploy to Production
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required: playbook filepath
          playbook: ansible/deploy.yml

          # Required: inventory file
          inventory: inventory/setup.yml

          # Required: SSH private key for authentication
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Required: remote user for SSH connection
          remote_user: admin

          # Required: host to deploy to
          host: ${{ secrets.HOST_CPE }}



